// Generated by https://quicktype.io

export interface Cliente {
  id_cliente?: number;
  dni:        number;
  nombres:    string;
  apellidos:  string;
  telefono:   string;
  email:      string;
}
