// Generated by https://quicktype.io

export interface Hotel {
  id_hotel?:      number;
  nombre:        string;
  direccion:     string;
  localidad:     string;
  provincia:     string;
  telefono:      number;
  num_estrellas: number;
}
