// Generated by https://quicktype.io

import { Cliente } from "./Cliente.interface";
import { Hotel } from "./Hotel.interface";
import { Sucursal } from "./Sucursal.interface";
import { Vuelo } from "./Vuelo.interface";

export interface Reserva {
  id_reserva?: number;
  clase:      string;
  vuelo:      Vuelo;
  cliente:    Cliente;
  hotel:      Hotel;
  sucursal:   Sucursal;
}
