// Generated by https://quicktype.io

export interface Vuelo {
  id?:                number;
  fecha_salida:       Date;
  hora_salida:        string;
  fecha_llegada:      Date;
  hora_llegada:       string;
  origen:             string;
  destino:            string;
  num_plazas_totales: number;
}
